### ISSUE TITLE
Crash on android version 5.0 

### ISSUE THREAD

**Issue by sachin-varshney** [AuthorizeNet/inperson-sdk-android#52]
java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                   at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                                   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                   at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                   at java.lang.Thread.run(Thread.java:818)
                                                                                **Caused by: java.lang.VerifyError: Rejecting class net.authorize.AuthNetField because it failed compile-time verification (declaration of 'net.authorize.AuthNetField' appears in /data/app/com.successive.logicspaybill-1/base.apk)**
                                                                                   at net.authorize.xml.XMLTransaction.addAuthentication(:66)
                                                                                   at net.authorize.xml.XMLTransaction.addAuthentication(:55)
                                                                                   at net.authorize.mobile.Transaction.toAuthNetPOSTString(:2142)
                                                                                   at net.authorize.util.HttpClient.ˏ(:79)
                                                                                   at net.authorize.util.HttpClient.executeXML(:280)
                                                                                   at net.authorize.Merchant.postTransaction(:416)
                                                                                   at com.successive.logicspaybill.async.LoginAsync.doInBackground(LoginAsync.java:132)
                                                                                   at com.successive.logicspaybill.async.LoginAsync.doInBackground(LoginAsync.java:32)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                   at java.lang.Thread.run(Thread.java:818) 
10-08 10:22:15.859 6386-6451/com.successive.logicspaybill E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                            Process: com.successive.logicspaybill, PID: 6386
                                                                            java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:818)
                                                                             Caused by: java.lang.VerifyError: Rejecting class net.authorize.AuthNetField because it failed compile-time verification (declaration of 'net.authorize.AuthNetField' appears in /data/app/com.successive.logicspaybill-1/base.apk)
                                                                                at net.authorize.xml.XMLTransaction.addAuthentication(:66)
                                                                                at net.authorize.xml.XMLTransaction.addAuthentication(:55)
                                                                                at net.authorize.mobile.Transaction.toAuthNetPOSTString(:2142)
                                                                                at net.authorize.util.HttpClient.ˏ(:79)
                                                                                at net.authorize.util.HttpClient.executeXML(:280)
                                                                                at net.authorize.Merchant.postTransaction(:416)
                                                                                at com.successive.logicspaybill.async.LoginAsync.doInBackground(LoginAsync.java:132)
                                                                                at com.successive.logicspaybill.async.LoginAsync.doInBackground(LoginAsync.java:32)
                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                at java.lang.Thread.run(Thread.java:818) 
10-08 10:22:16.331 6386-6386/com.successive.logicspaybill E/WindowManager: android.view.WindowLeaked: Activity com.successive.logicspaybill.activities.LoginActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{21cd8156 V.E..... R......D 0,0-576,116} that was originally added here
                                                                               at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
                                                                               at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:261)
                                                                               at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                               at android.app.Dialog.show(Dialog.java:298)
                                                                               at com.successive.logicspaybill.async.LoginAsync.onPreExecute(LoginAsync.java:63)
                                                                               at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)
                                                                               at android.os.AsyncTask.execute(AsyncTask.java:535)
                                                                               at com.successive.logicspaybill.activities.LoginActivity$1.onClick(LoginActivity.java:79)
                                                                               at android.view.View.performClick(View.java:4756)
                                                                               at android.view.View$PerformClick.run(View.java:19749)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by sachin-varshney** [comment]
public class LoginAsync extends AsyncTask<Void, Void, SoapObject> {

    private String SOAP_ACTION = "";
    private String METHOD_NAME = "Login";

    private String userName = "";
    private String passWord = "";

    private Context context;
    private TaskCompleted taskCompleted;

    private ProgressDialog progressDialog;

    public LoginAsync(Context context, String userName, String passWord) {
        this.context = context;
        this.userName = userName;
        this.passWord = passWord;
        this.taskCompleted = (TaskCompleted) context;
    }


    @Override
    protected void onPreExecute() {
        super.onPreExecute();

        SpannableString msg = new SpannableString("Verifying...");
        msg.setSpan(new RelativeSizeSpan(1.5f), 0, msg.length(), 0);

        progressDialog = new ProgressDialog(context);
        progressDialog.setMessage(msg);
        progressDialog.setCancelable(false);
        progressDialog.show();
    }

    @Override
    protected SoapObject doInBackground(Void... voids) {

        SOAP_ACTION = Constants.NAME_SPACE + METHOD_NAME;

        //Initialize soap request + add parameters
        SoapObject request = new SoapObject(Constants.NAME_SPACE, METHOD_NAME);


        PropertyInfo user = new PropertyInfo();
        user.setName("username");
        user.setValue(userName);
        user.setType(String.class);
        request.addProperty(user);

        PropertyInfo pwd = new PropertyInfo();
        pwd.setName("password");
        pwd.setValue(passWord);
        pwd.setType(String.class);
        request.addProperty(pwd);

        //Declare the version of the SOAP request
        SoapSerializationEnvelope envelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);

        envelope.setOutputSoapObject(request);

        log("request1:      " + request);

        envelope.dotNet = true;

        try {
            HttpTransportSE androidHttpTransport = new HttpTransportSE(Constants.URL);

            //this is the actual part that will call the webservice
            androidHttpTransport.call(SOAP_ACTION, envelope);

            if (envelope.bodyIn instanceof SoapFault) {
                String str = ((SoapFault) envelope.bodyIn).faultstring;
                log("Soap Fault:        " + str);
                Toast.makeText(context, "Invalid Credential", Toast.LENGTH_LONG).show();
            } else {
                SoapObject response = (SoapObject) envelope.bodyIn;

                log("response0:  " + response.toString());
                StringBuffer result;
                result = new StringBuffer(response.toString());
                log("String Result:     " + result);


                /*************************/

                net.authorize.mobile.Result resultAU;
                String deviceID = "Test EMV Android";
                PasswordAuthentication passAuth = PasswordAuthentication.createMerchantAuthentication(Constants.AUTH_NAME, Constants.AUTH_SECRET, deviceID);

                Constants.merchant = Merchant.createMerchant(Environment.PRODUCTION, passAuth);

                net.authorize.mobile.Transaction transaction = Constants.merchant
                        .createMobileTransaction(net.authorize.mobile.TransactionType.MOBILE_DEVICE_LOGIN);

                MobileDevice mobileDevice = MobileDevice.createMobileDevice(deviceID,
                        "Device description", "425-555-0000", "Android");

                transaction.setMobileDevice(mobileDevice);
    **// App is crashing at this point**
                resultAU = (net.authorize.mobile.Result) Constants.merchant
                        .postTransaction(transaction);

                if (resultAU.isOk()) {

                    try {
                        SessionTokenAuthentication sessionTokenAuthentication = SessionTokenAuthentication
                                .createMerchantAuthentication(Constants.merchant
                                        .getMerchantAuthentication().getName(), resultAU
                                        .getSessionToken(), "Test EMV Android");
                        if ((resultAU.getSessionToken() != null)
                                && (sessionTokenAuthentication != null)) {
                            Constants.merchant
                                    .setMerchantAuthentication(sessionTokenAuthentication);

//                        handler.sendEmptyMessage(0);
//                            Util.setMerchant(Constants.merchant, context);
                        }
                    } catch (Exception ex) {

                    }
                } else {
//                handler.sendEmptyMessage(1);
                    Log.e("EMVResponse", resultAU.getXmlResponse());
//                    Toast.makeText(context, result.getXmlResponse(),Toast.LENGTH_SHORT).show();
                }

/*************************/


                return response;
            }


        } catch (Exception e) {
            e.printStackTrace();
            log("" + e.toString());


        }

        return null;

    }

    @Override
    protected void onPostExecute(SoapObject response) {
        super.onPostExecute(response);
        progressDialog.dismiss();

        if (response == null) {
            Toast.makeText(context, "Invalid Credential", Toast.LENGTH_LONG).show();
            log("Invalid Credentials");
        } else if (response.hasProperty("LoginResult")) {
            //request success and received expecting data
            parsingLoginResponse(response);
        } else {
            Toast.makeText(context, "Invalid Credential", Toast.LENGTH_LONG).show();
            log("Data Error");
        }


    }


    private void parsingLoginResponse(SoapObject response) {
        for (int i = 0; i < response.getPropertyCount(); i++) {

            PropertyInfo pi = new PropertyInfo();
            response.getPropertyInfo(i, pi);
            Object property = response.getProperty(i);
            log("Properties:        " + property);
            if (pi.name.equals("LoginResult")) {
                //getting object properties
                String token = response.getPrimitivePropertyAsString("LoginResult");

                if (!token.equals("")) {
                    Util.storeToken(token.toString(), context);
                    taskCompleted.onTaskComplete(token.toString());
                } else {
                    Toast.makeText(context, "Invalid Credential", Toast.LENGTH_LONG).show();

                }

                log("Parsing Token Result:      " + token);
            }
        }
    }

    private void log(String msg) {
        Log.i("Tag", "" + msg);
    }
}








App is crashing at api level 21 only and above this it is working fine.
